model:
  max_iter: 1000
  random_state: 42
  tolerance: 1e-4

mlflow:
  host: "http://128.0.1.1:8080"
  experiment: "pavel_p_mlops_hw2"
  run_name: "logistic_regression"

tensorboard:
  folder_path: "../runs"